apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
  namespace: dev
data:
  CONFIG_SERVER_URL: "http://config-service:8888"
  USER_MANAGEMENT_SERVICE_URL: "http://user-management-service:8081"
  JWT_ISSUER: "http://auth-server:9000"
